- name: Download Docker Compose
  get_url:
    url: "https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64"
    dest: "/usr/local/bin/docker-compose"
    mode: '0755'

- name: Create a symlink for Docker Compose
  file:
    src: /usr/local/bin/docker-compose
    dest: /usr/bin/docker-compose
    state: link

- name: Verify Docker Compose installation
  command: docker-compose version
  register: compose_version
  ignore_errors: yes

- name: Display Docker Compose version
  debug:
    msg: "{{ compose_version.stdout_lines }}"

- name: Ensure target directory exists
  file:
    path: /opt/monitoring
    state: directory
    mode: '0755'

- name: Copy configuration files
  copy:
    src: "{{ item }}"
    dest: "/opt/monitoring/{{ item | basename }}"
    mode: '0644'
  loop:
    - alertmanager.yml
    - alert.rules.yml
    - docker-compose.yml
    - prometheus.yml

- name: Start monitoring stack using Docker Compose
  command: /usr/local/bin/docker-compose up -d
  args:
    chdir: /opt/monitoring

- name: Verify running containers
  command: docker ps
  register: result

- name: Display running containers
  debug:
    msg: "{{ result.stdout_lines }}"

